### ISSUE TITLE
bug: overflow errors for too long fields

### ISSUE THREAD

**Issue by Zer0Legion** [AY2324S2-CS2103T-T10-1/tp#171]
![image](https://github.com/AY2324S2-CS2103T-T10-1/tp/assets/92260463/5de572c7-c0dd-4605-97c9-bd403262729b)

eg. for a too long address, the UI will not show the full address (...)
Suggestions to fix:
enforce a length (128 chars)?
change UI to show entire thing? -> may cause antagonistic testers to spam 1k+ characters

**Comment by delishad21** [comment]
Fixed with #287
