### ISSUE TITLE
Add csv formatting styles accepted for import and importExam in UG

### ISSUE THREAD

**Issue by delishad21** [AY2324S2-CS2103T-T10-1/tp#266]
ImportExamScores: (DONE)
1. email must be first column
2. only existing exam details will be imported
3. exam headers in the csv file must follow the format "Exam:EXAMNAME"

Import:
1. CSV file must contain headers named after the compulsory fields
2. As long as the compulsory fields are present, the app can import
3. rows with invalid values will be skipped and added to an error report

**Comment by Zer0Legion** [comment]
My PR on this issue has been merged. Awaiting updates from @Pughal77

**Comment by Pughal77** [comment]
My PR addresses these issues!

**Comment by jayllo-c** [comment]
@Pughal77 has completed his import command and @danielleloh has documented the correct Csv formatting styles users should use!
