### ISSUE TITLE
[PE-D][Tester D] Phone number looks confusing without spaces after area code

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-1/tp#342]
With an area code followed by a phone number, the phone number follows immediately after the area code, making it confusing for the user, who does not know which number corresponds to the area code or the phone number.

![image.png](https://raw.githubusercontent.com/joelgoh1/ped/main/files/8848f212-2f28-49d8-a2e3-a44a7bf7cd4a.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: joelgoh1/ped#5

**Comment by delishad21** [comment]
For this context of our application, the user just needs all the information he might need to contact the record. For an overseas number, having this amount of information would be sufficient for the user. There is no need for the user to know what the area code is
