### ISSUE TITLE
[PE-D][Tester D] Sample data tags not very representative of the problem

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-1/tp#349]
![image.png](https://raw.githubusercontent.com/joelgoh1/ped/main/files/954cc0cc-4f06-4579-826e-0834dfc9ba0a.png)

Current tags for sample data do not seem to reflect the nature of CS1101 Tutor storing their students information. This might be confusing for a new user trying out the sample data.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: joelgoh1/ped#7

**Comment by delishad21** [comment]
Add this to planned enhancements in DG

**Comment by delishad21** [comment]
Closed as this has been added to planned enhancements
