### ISSUE TITLE
[PE-D][Tester C] Copy Command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-1/tp#357]
## Describe the bug
After Copy, when I paste there is a semicolon at the back when its not suppose to be there.

## Expected behavior
email should not have semicolon

## Priority
p3

## Screenshots/Video

![image.png](https://raw.githubusercontent.com/headcube1/ped/main/files/032f2505-e2a4-4d09-b77b-966f64fbe427.png)

![image.png](https://raw.githubusercontent.com/headcube1/ped/main/files/c30e5910-d2d2-4750-89d5-811469240cad.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: headcube1/ped#7

**Comment by jayllo-c** [comment]
This is not considered a functionality bug because the semicolon symbol is a delimiter ('separator') between email addresses, and will allow the full set of emails to be treated correctly by the email-sending platforms.

**Comment by jayllo-c** [comment]
Perhaps this can be reflected better in the UG
