### ISSUE TITLE
[PE-D][Tester E] No error thrown when email does not fulfil constraint

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-1/tp#363]
## Description of the Bug
Application accepts the email input when it did not fulfil the constraints for it. The constraint that it did not meet is: `Made up of domain labels followed by periods`

## Steps to Reproduce
1. `add n|test p|98765432 e|1@12 a|normal address`

## Expected behavior
Throws an error message on invalid email

## Actual behavior
Accepts the email and add person
![image.png](https://raw.githubusercontent.com/tsulim/ped/main/files/db544466-47de-47e1-bc40-a1871a069be3.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: tsulim/ped#4

**Comment by delishad21** [comment]
@jayllo-c what are your thoughts on the phrasing of our constraint?

**Comment by delishad21** [comment]
For now ill change it to `The domain name is made up of domain labels which may be separated by periods.`
