### ISSUE TITLE
[PE-D][Tester B] Unnecessary constraint on score

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-1/tp#371]
Under the "Command Parameter Summary" section of user guide, the parameter for the prefix `[s| ]` is constrained to be integers. However, the maximum length of the parameter (7 + 2 decimals) seem to suggest that it can be non-integers as well.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: chin-herng/ped#5

**Comment by jayllo-c** [comment]
The whole point of this is to accommodate changes in the exam that could potentially result in the max score becoming a decimal (e.g. section worth 0.5 marks wrongly phrased and hence excluded from the exam)
