### ISSUE TITLE
[PE-D][Tester B] Unused documented prefixes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T10-1/tp#372]
In the "Command Parameter Summary" section of the user guide, the prefixes `[lt| ]` and `[mt| ]` are documented but are not mentioned elsewhere in the features documentation.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: chin-herng/ped#6

**Comment by jayllo-c** [comment]
Can be used in the information section of the find command part of the guide
