### ISSUE TITLE
DG: Re-format

### ISSUE THREAD

**Issue by Zer0Legion** [AY2324S2-CS2103T-T10-1/tp#396]
Reformat the DG after multiple merges.

- [x] Re-arrange implementations portion to have the same command flow as UG
- [x] Re-arrange manual testing to follow UG flow
- [x] Re-format manual testing sections to have consistent format
- [x] Ensure headers have consistent naming and hierachy
- [ ] Reformat images to proper size

**Comment by delishad21** [comment]
Did not fully follow UG flow as UG has import as the first function. Import uses the addCommand and logically it makes more sense to introduce the importCommand only after we have explained the addCommand
